{
 "title": "Painel OTRS",
 "time": { "from": "2020-07-26T20:51:32.694Z", "to": "2020-08-27T20:51:32.694Z" },
 "panels": [
  {
   "title": "Chamados Novos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM ticket where ticket_state_id = '1';"
    }
   ]
  },
  {
   "title": "Tickets sem Atendente",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM ticket where  user_id = 1;"
    }
   ]
  },
  {
   "title": "Chamados sem Atualização (7 Dias)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM ticket WHERE (ticket_state_id = '4' OR ticket_state_id = '6') AND (change_time <= now() - INTERVAL 7 DAY);"
    }
   ]
  },
  {
   "title": "Total de ticket pendentes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM ticket WHERE ticket_state_id = 6"
    }
   ]
  },
  {
   "title": "Chamados Abertos por Fila",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\nnow() as time,\r\nqueue.name AS FILA, \r\ncount(*) AS QUANTIDADE\r\nFROM ticket INNER JOIN queue ON ticket.queue_id = queue.id \r\nWHERE (ticket_state_id = '4' OR ticket_state_id = '6' OR ticket_state_id = '1'  ) \r\nGROUP BY queue.name;"
    }
   ]
  },
  {
   "title": "Tickets abertos hoje",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM ticket WHERE create_time >= CURDATE();"
    }
   ]
  },
  {
   "title": "Total de ticket abertos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM ticket WHERE (ticket_state_id = 1) or (ticket_state_id = 4) or (ticket_state_id = 6) or (ticket_state_id = 7) or (ticket_state_id = 8) or (ticket_state_id = 9)"
    }
   ]
  },
  {
   "title": "Tickets fechados hoje",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\nCOUNT(*)\r\nFROM ticket \r\nINNER JOIN ticket_state ON ticket.ticket_state_id = ticket_state.id\r\nINNER JOIN ticket_history ON ticket_history.ticket_id = ticket.id\r\n\r\nWHERE (ticket_history.state_id = \"2\") and (ticket_history.history_type_id = \"27\") and (ticket_history.change_time >= now() - INTERVAL 1 DAY);"
    }
   ]
  }
 ]
}