version: '2'
services:
  otrs_app:
    restart: always
    image: infracerta/otrs_app
    container_name: otrs_app
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    networks:
      - otrs_net

  otrs_database:
    restart: always
    image: infracerta/otrs_database:latest
    container_name: otrs_database
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    networks:
      - otrs_net

networks:
   otrs_net:
     driver: bridge
